FORMAT: 1A
HOST: http://elections.parseapp.com/

# Elections

Elections is a simple and free API allowing easy access to information on US presidential and congressional elections.
**Coming soon:**
+ Congressional election data

# Elections API Root [/]

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "elections_url": "/elections"
        }

## Group Election

Resources related to elections in the API.

## Election [/elections/{year}/{type}]

An Election object has the following attributes:

+ year
+ type
+ totalVotes - Total number of votes cast in election.
+ votingAge - U.S. Census Bureau voting age population.
+ dataTypes - Valid data types for this election.
+ url

+ Parameters
    + year: 2012 (required, string) - Year of the election. If election type is presidential, must be a presidential federal election year.
        + Members
            + `2004`
            + `2006`
            + `2008`
            + `2010`
            + `2012`
    + type: presidential (required, string) - Type of election.
        + Members
            + `presidential`
            + `congressional`

### View an Election [GET]

+ Response 200 (application/json)

        {
          "year": "2012",
          "type": "presidential",
          "totalVotes": 129085403,
          "votingAge": 235248000,
          "dataTypes": [
            "popularvote",
            "electoralstatevote"
          ],
          "url": "/elections/2012/presidential"
        }


## Election data [/elections/{year}/{type}/data/{data_type}]

### Get popular vote information [GET]

+ Parameters
    + year: 2012 (required, year) - Year of election. If election type is presidential, must be a presidential federal election year.
        + Members
            + `2004`
            + `2006`
            + `2008`
            + `2010`
            + `2012`
    + type: presidential (required) - Type of election.
        + Members
            + `presidential`
            + `congressional`
    + data_type: popularvote (required)
        + Members
            + `popularvote` - Array consisting of vote information on each candidate.
            + `electoralstatevote` - Array consisting of per-state electoral vote information on the top two candidates.
            

+ Response 200 (application/json)

        {
          "year": "2012",
          "type": "presidential",
          "popularVote": [
            {
              "candidate": "Barack Obama",
              "parties": [
                "Democrat"
              ],
              "voteTotal": 65915796
            },
            {
              "candidate": "Mitt Romney",
              "parties": [
                "Republican"
              ],
              "voteTotal": 60933500
            },
            {
              "candidate": "Gary Johnson",
              "parties": [
                "Libertarian",
                "Independent"
              ],
              "voteTotal": 1275971
            },
            {
              "candidate": "Jill Stein",
              "parties": [
                "Green",
                "Pacific Green",
                "Mountain",
                "Independent"
              ],
              "voteTotal": 469628
            },
            {
              "candidate": "Write-In",
              "parties": [
                "Miscellaneous"
              ],
              "voteTotal": 136040
            },
            {
              "candidate": "Virgil Goode",
              "parties": [
                "Constitution",
                "Independent American",
                "U.S. Taxpayers"
              ],
              "voteTotal": 122388
            },
            {
              "candidate": "Roseann Barr",
              "parties": [
                "Peace and Freedom"
              ],
              "voteTotal": 67326
            },
            {
              "candidate": "Ross C. \"Rocky\" Anderson",
              "parties": [
                "Justice",
                "Progressive",
                "Independent"
              ],
              "voteTotal": 43018
            },
            {
              "candidate": "Tom Hoefling",
              "parties": [
                "American Independent",
                "America's Party"
              ],
              "voteTotal": 40628
            },
            {
              "candidate": "Randall Terry",
              "parties": [
                "Independent"
              ],
              "voteTotal": 13105
            },
            {
              "candidate": "Richard Duncan",
              "parties": [
                "Independent"
              ],
              "voteTotal": 12557
            },
            {
              "candidate": "Peta Lindsay",
              "parties": [
                "Socialism and Liberation"
              ],
              "voteTotal": 7791
            },
            {
              "candidate": "None of These Candidates",
              "parties": [
                "Nevada"
              ],
              "voteTotal": 5770
            },
            {
              "candidate": "Chuck Baldwin",
              "parties": [
                "Reform"
              ],
              "voteTotal": 5017
            },
            {
              "candidate": "Will Christensen",
              "parties": [
                "Constitution"
              ],
              "voteTotal": 4453
            },
            {
              "candidate": "Stewart Alexander",
              "parties": [
                "Socialist"
              ],
              "voteTotal": 4405
            },
            {
              "candidate": "James Harris",
              "parties": [
                "Socialist Workers"
              ],
              "voteTotal": 4117
            },
            {
              "candidate": "Thomas Robert Stevens",
              "parties": [
                "Objectivist"
              ],
              "voteTotal": 4091
            },
            {
              "candidate": "Jim Carlson",
              "parties": [
                "Grassroots"
              ],
              "voteTotal": 3149
            },
            {
              "candidate": "Jill Reed",
              "parties": [
                "Unaffiliated"
              ],
              "voteTotal": 2875
            },
            {
              "candidate": "Merlin Miller",
              "parties": [
                "American Third Position",
                "Independent"
              ],
              "voteTotal": 2701
            },
            {
              "candidate": "Sheila \"Samm\" Tittle",
              "parties": [
                "We the People)"
              ],
              "voteTotal": 2572
            },
            {
              "candidate": "Gloria La Riva",
              "parties": [
                "Socialism and Liberation",
                "Independent"
              ],
              "voteTotal": 1608
            },
            {
              "candidate": "Jerry White",
              "parties": [
                "Socialist Equality",
                "Independent"
              ],
              "voteTotal": 1279
            },
            {
              "candidate": "Dean Morstad",
              "parties": [
                "Constitutional Government"
              ],
              "voteTotal": 1094
            },
            {
              "candidate": "Jerry Litzel",
              "parties": [
                "Independent"
              ],
              "voteTotal": 1027
            },
            {
              "candidate": "Barbara Dale Washer",
              "parties": [
                "Reform"
              ],
              "voteTotal": 1016
            },
            {
              "candidate": "Jeff Boss",
              "parties": [
                "NSA Did 911"
              ],
              "voteTotal": 1007
            },
            {
              "candidate": "Andre Barnett",
              "parties": [
                "Reform"
              ],
              "voteTotal": 956
            },
            {
              "candidate": "Jack Fellure",
              "parties": [
                "Prohibition"
              ],
              "voteTotal": 518
            }
          ],
          "url": "/elections/2012/presidential/data/popularvote"
        }