FORMAT: 1A
HOST: http://elections.parseapp.com/

# Elections

Elections is a simple and free API allowing easy access to information on US presidential and congressional elections.
**Coming soon:**
+ Congressional election data

# Elections API Root [/]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

It is recommend to follow the “url” link values,
[Link](https://tools.ietf.org/html/rfc5988) or Location headers where
applicable to retrieve resources. Instead of constructing your own URLs,
to keep your client decoupled from implementation details.

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "elections_url": "/elections"
        }

## Group Election

Resources related to elections in the API.

## Election [/elections/{year}/{type}]

An Election object has the following attributes:

+ year
+ type
+ totalVotes - Total number of votes cast in election.
+ votingAge - U.S. Census Bureau voting age population.
+ dataTypes - Valid data types for this election.
+ url

+ Parameters
    + year: 2012 (required, string) - Year of the election. If election type is presidential, must be a presidential federal election year.
        + Members
            + `2004`
            + `2006`
            + `2008`
            + `2010`
            + `2012`
    + type: presidential (required, string) - Type of election.
        + Members
            + `presidential`
            + `congressional`

### View an Election [GET]

+ Response 200 (application/json)

        {
            "totalVotes": 129085403,
            "type": "presidential",
            "votingAge": 235248000,
            "year": "2012"
        }


## Election data [/elections/{year}/{type}/data/{data_type}]

### Get popular vote information [GET]
+ year
+ type
+ url

+ Parameters
    + year: 2012 (required, year) - Year of election. If election type is presidential, must be a presidential federal election year.
        + Members
            + `2004`
            + `2006`
            + `2008`
            + `2010`
            + `2012`
    + type: presidential (required) - Type of election.
        + Members
            + `presidential`
            + `congressional`
    + data_type: popularvote (required)
        + Members
            + `popularvote` - Array consisting of vote information on each candidate.
            + `electoralstatevote` - Array consisting of per-state electoral vote information on the top two candidates.