FORMAT: 1A
HOST: http://elections.parseapp.com/

# Elections

Elections is a simple and free API allowing easy access to information on US presidential and congressional elections.

# Elections API Root [/]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

It is recommend to follow the “url” link values,
[Link](https://tools.ietf.org/html/rfc5988) or Location headers where
applicable to retrieve resources. Instead of constructing your own URLs,
to keep your client decoupled from implementation details.

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)

        {
            "elections_url": "/elections"
        }

## Group Election

Resources related to elections in the API.

## Election [/elections/{year}/{election}]

An Election object has the following attributes:

+ year
+ type
+ totalVotes - Total number of votes cast in election.
+ votingAge - U.S. Census Bureau voting vge population.
+ popularVote - Array consisting of vote information on each candidate.
+ electoralStateVote - Array consisting of per-state electoral vote information on the top two candidates.
+ url

+ Parameters
    + year: 2012 (required, string) - Year of the election. Must be one of [2004,2006,2008,2010,2012]. If election type is presidential, must be a presidential federal election year.
    + election: presidential (required, string) - Type of election. Must be one of [presidential,senate,house].

### View an Election Detail [GET]

+ Response 200 (application/json)

        {
            "totalVotes": 129085403,
            "type": "presidential",
            "votingAge": 235248000,
            "year": "2012"
        }


## Election data [/elections/{year}/{type}/data/{data_type}]

+ Parameters
    + year: 2012 (required, number) - ID of the Question in form of an integer
    + type: presidential (required)
    + data_type: popularvote (required) - For presidential elections, one of [popularvote,electoralstateVote]

### Get popular vote information [GET]